language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: ThZUSejaoltST4coO8ERsYQzoNxac95NRHtwYfOePGXmBVd5sIMV8rH25Zh+mC0Fhqoau9IwZ0PJWRB8yhp0DcI3rSHTSu50F2QiFOEJF7+GeYaoz7LORfiI7VVuea+yZGm+o+0/jPQ5lHwER1NO0BialW1URt7IDuu6toOPxO43b+lwn4micGnvjvhRhcB+sWD/vOyiA3JtNgKx4dJgjQeZ2NFO2iLDnzGZnIGHV7VVAn7rXs7QdwFvK485PcEUl036De9n/hpC41JAS1AAot4kXvJgezZCAC8VmlAEglfLIKYKu4Ybf1Ir98/Ug7JWnNnrC6nCRWD4TG1muAkcORyJQ/37MnZiB3QBRWAmghIjZSovFfCV7UiUdQY3220iMrg8HyU3WfA9jIROe8Z+x4x+BQC630Ks/Yr7WJGxIIQGIcqnQeyQUMnysG4oiKpwGkvjE1M93VfZBAiX2SLYqOwdyZqM+TEsIW1D3COFLO3zazGk4+SrtNlo2tp5xyJc5yCXww2S7uIq91ZyrHUMn8652Q32w4+34MfLKWRg5YGAW9JwEYmcXrm9jFQZ8ebX0QVp4J0dM1ME/PQw0uwNwECn5tfCBhon8/OnFAa72/5FtcdDaks7epdj5MEsIQjQ7VvyKl2RKZ2xmxje8c4u932Z/mxnLkdmNQNdgHd1eP4=
  app: cs3240-a03
  on:
    repo: uva-cs3240-s21/project-a-03
