# Generated by Django 3.1.6 on 2021-03-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
