# Generated by Django 3.2 on 2021-04-12 20:15

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('CARDIO', 'Cardio'), ('WEIGHT_TRAINING', 'Weight Training'), ('FLEXIBILITY', 'Flexibility'), ('ARMS', 'Arms'), ('LEGS', 'Legs'), ('BACK', 'Back'), ('CORE', 'Core'), ('CHEST', 'Chest')], default='Cardio', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Goal_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('CARDIO', 'Cardio'), ('WEIGHT_TRAINING', 'Weight Training'), ('FLEXIBILITY', 'Flexibility'), ('ARMS', 'Arms'), ('LEGS', 'Legs'), ('BACK', 'Back'), ('CORE', 'Core'), ('CHEST', 'Chest')], default='Cardio', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=200, null=True)),
                ('private', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='no author', max_length=200)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exercising.group')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=4), default=0, size=8)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='goal_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='exercising.profile'),
        ),
        migrations.AddField(
            model_name='exercise_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exercising.profile'),
        ),
    ]
