# Generated by Django 3.1.6 on 2021-04-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0002_auto_20210418_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_log',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal_log',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points_calis',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points_cardio',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points_weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
