# Generated by Django 3.2 on 2021-04-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0002_auto_20210412_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exercising.profile'),
        ),
        migrations.AddField(
            model_name='goal_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='exercising.profile'),
        ),
    ]
