# Generated by Django 3.2 on 2021-04-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0002_auto_20210412_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise_log',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='goal_log',
            old_name='user',
            new_name='profile',
        ),
    ]
