# Generated by Django 3.1.6 on 2021-03-27 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0003_auto_20210327_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_log',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='exercise_log',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exercise_log',
            name='exercise_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
