# Generated by Django 3.1.6 on 2021-04-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0003_auto_20210412_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
