# Generated by Django 3.2 on 2021-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0003_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
