# Generated by Django 3.1.6 on 2021-04-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0003_auto_20210418_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_total',
            field=models.IntegerField(default=0),
        ),
    ]
