# Generated by Django 3.1.7 on 2021-04-05 01:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercising', '0004_auto_20210327_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('current_date', models.DateField(default=datetime.date.today)),
                ('future_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('future_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.ManyToManyField(blank=True, to='exercising.Goal_Log'),
        ),
    ]
