# Generated by Django 3.1.6 on 2021-04-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0004_remove_profile_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='google_user',
        ),
    ]
