# Generated by Django 3.2 on 2021-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0004_auto_20210418_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_log',
            name='exercise_type',
            field=models.CharField(choices=[('CARDIO', 'Cardio'), ('WEIGHT_TRAINING', 'Weight Training'), ('FLEXIBILITY', 'Flexibility')], default='Cardio', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal_log',
            name='exercise_type',
            field=models.CharField(choices=[('CARDIO', 'Cardio'), ('WEIGHT_TRAINING', 'Weight Training'), ('FLEXIBILITY', 'Flexibility')], default='Cardio', max_length=20),
        ),
    ]
