# Generated by Django 3.1.6 on 2021-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0004_profile_points_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
