# Generated by Django 3.1.6 on 2021-04-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0006_auto_20210404_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal_log',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='goal_log',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='goal_log',
            name='future_date',
        ),
        migrations.RemoveField(
            model_name='goal_log',
            name='future_weight',
        ),
        migrations.RemoveField(
            model_name='goal_log',
            name='user',
        ),
    ]
