# Generated by Django 3.2 on 2021-04-18 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0006_auto_20210418_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=3),
        ),
    ]
