# Generated by Django 3.1.6 on 2021-04-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0007_auto_20210405_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal_log',
            name='date',
        ),
    ]
