# Generated by Django 3.1.6 on 2021-04-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercising', '0009_group_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-pub_date']},
        ),
    ]
